### ISSUE TITLE
Bot join & leave issue

### ISSUE THREAD

**Issue by lx78WyY0J5** [Altherneum/bot#1]
The message is not sent to the channel : `1081941748240089158`

**Comment by lx78WyY0J5** [comment]
```
java.io.IOException: Permission denied
        at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at altherneum.fr.api.FileSystem.BanqueRoute(FileSystem.java:42)
        at altherneum.fr.listener.casinoBanqueroute.setTotal(casinoBanqueroute.java:163)
        at altherneum.fr.listener.casinoBanqueroute$2.run(casinoBanqueroute.java:173)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
java.io.IOException: Permission denied
        at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at altherneum.fr.api.FileSystem.BanqueRoute(FileSystem.java:42)
        at altherneum.fr.listener.casinoBanqueroute.setTotal(casinoBanqueroute.java:163)
        at altherneum.fr.listener.casinoBanqueroute$2.run(casinoBanqueroute.java:173)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
java.io.IOException: Permission denied
        at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at altherneum.fr.api.FileSystem.BanqueRoute(FileSystem.java:42)
        at altherneum.fr.listener.casinoBanqueroute.setTotal(casinoBanqueroute.java:163)
        at altherneum.fr.listener.casinoBanqueroute$2.run(casinoBanqueroute.java:173)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
java.io.IOException: Permission denied
        at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at altherneum.fr.api.FileSystem.BanqueRoute(FileSystem.java:42)
        at altherneum.fr.listener.casinoBanqueroute.setTotal(casinoBanqueroute.java:163)
        at altherneum.fr.listener.casinoBanqueroute$2.run(casinoBanqueroute.java:173)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
2024-10-05 13:54:29.080+0200 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Websocket closed with reason 'Discord commanded a reconnect (Received opcode 7)' and code COMMANDED_RECONNECT (4999) by client!
2024-10-05 13:54:29.083+0200 INFO org.javacord.core.util.gateway.DiscordWebSocketAdapter Trying to reconnect/resume in 1 seconds!
java.io.IOException: Permission denied
        at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at altherneum.fr.api.FileSystem.BanqueRoute(FileSystem.java:42)
        at altherneum.fr.listener.casinoBanqueroute.setTotal(casinoBanqueroute.java:163)
        at altherneum.fr.listener.casinoBanqueroute$2.run(casinoBanqueroute.java:173)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
java.io.IOException: Permission denied
        at java.base/java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.base/java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:258)
        at java.base/java.io.File.createNewFile(File.java:1045)
        at altherneum.fr.api.FileSystem.file(FileSystem.java:12)
        at altherneum.fr.listener.CheckInvite.onCheckInvite(CheckInvite.java:62)
        at altherneum.fr.listener.JoinLeaveListener.lambda$MemberJoinListener$1(JoinLeaveListener.java:54)
        at org.javacord.core.util.event.EventDispatcher.lambda$dispatchServerMemberJoinEvent$249(EventDispatcher.java:8406)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$dispatchEvent$12(EventDispatcherBase.java:213)
        at org.javacord.core.util.event.EventDispatcherBase.lambda$checkRunningListenersAndStartIfPossible$20(EventDispatcherBase.java:281)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by lx78WyY0J5** [comment]
Permission Linux KO ?
